// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $account_index from "./routes/account/index.tsx";
import * as $account_manage from "./routes/account/manage.ts";
import * as $account_upgrade from "./routes/account/upgrade.ts";
import * as $api_stripe_webhooks from "./routes/api/stripe-webhooks.ts";
import * as $api_users_login_index from "./routes/api/users/[login]/index.ts";
import * as $api_users_index from "./routes/api/users/index.ts";
import * as $index from "./routes/index.tsx";
import * as $pricing from "./routes/pricing.tsx";
import * as $users_login_ from "./routes/users/[login].tsx";
import * as $welcome from "./routes/welcome.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/account/index.tsx": $account_index,
    "./routes/account/manage.ts": $account_manage,
    "./routes/account/upgrade.ts": $account_upgrade,
    "./routes/api/stripe-webhooks.ts": $api_stripe_webhooks,
    "./routes/api/users/[login]/index.ts": $api_users_login_index,
    "./routes/api/users/index.ts": $api_users_index,
    "./routes/index.tsx": $index,
    "./routes/pricing.tsx": $pricing,
    "./routes/users/[login].tsx": $users_login_,
    "./routes/welcome.tsx": $welcome,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
